### PR TITLE
Transitive project-defined compilerDeps

### PR DESCRIPTION
**Pull request by megri**
I'm leaving town tomorrow so I wanted to publish my progress so far. I'm still not sure if this is the right way to solve the issue, but please have a look and see if it somewhat fits the bill. :)

### CODE REVIEW

**Comment by tindzk** [comment]
Looks great! Could you also add the new setting to the README?

**Comment by megri** [comment]
As soon as I'm back home, which may be a couple of days from now. :)

**Comment by megri** [comment]
I've just updated the documentation and rebased on top of latest master.

**Comment by tindzk** [comment]
Perfect. Thanks for your contribution!

**Pull request merged**
